language: rust
rust:
  - nightly
script:
  - cargo build --verbose --all
  - cargo run -p rider-generator
  - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || echo 0
  - cargo tarpaulin --all --ciserver circle-ci --out Xml
  - wget -O - -q "https://codecov.io/bash" > .codecov
  - chmod +x .codecov
  - ./.codecov -t $CODECOV_TOKEN
  - echo "Uploaded code coverage"
env:
  - CODECOV_TOKEN: "e58da505-19f2-481c-8068-e845cb36fbe4"
  - TZ: "/usr/share/zoneinfo/Europe/Paris"
  - rider-config: "1"
before_install:
  - export XDG_RUNTIME_DIR=$(pwd)
  - export XDG_BIN_HOME=$HOME/.local/bin
  - sudo apt-get install -y -qq xvfb mesa-utils mesa-vdpau-drivers
  - sudo apt-get install -y libssl-dev pkg-config cmake zlib1g-dev
  - sudo apt-get install -q -y libsdl2-dev libsdl2-2.0-0 libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
addons:
  apt:
    update: true
