[package]
name = "editor"
version = "0.1.0"
authors = ["Adrian Wozniak <adrian.wozniak@ita-prog.pl>"]
edition = "2018"

[dependencies]
rand = "0.5"
plex = "*"
dirs = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"

[dependencies.sdl2]
version = "0.31.0"
features = ["gfx", "image", "mixer", "ttf"]
