version: 2.1

jobs:
  build:
    working_directory: ~/rider
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: abronan/rust-circleci:latest

    environment:
      # Set your codecov token if your repository is private.
      CODECOV_TOKEN: "e58da505-19f2-481c-8068-e845cb36fbe4"
      TZ: "/usr/share/zoneinfo/Europe/Paris"
#      XDG_RUNTIME_DIR: "$HOME/rider"

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get install -y -qq xvfb mesa-utils mesa-vdpau-drivers
            apt-get install -q -y libsdl2-dev libsdl2-2.0-0 libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt -- --error-on-unformatted --unstable-features --check
      - run:
          name: Nightly Build
          command: |
            rustup run nightly rustc --version --verbose
            rustup run nightly cargo --version --verbose
            rustup run nightly cargo build
      - run:
          name: Test
          command: |
            Xvfb :5 -screen 0 800x600x24 +extension GLX +render -noreset &
            export DISPLAY=:5
            export XDG_RUNTIME_DIR=$(pwd)
            rustup run nightly cargo test
      - run:
          name: Upload Coverage
          command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"
